/**
 * Custom migration script for Neon (bypasses TCP port 5432 restrictions).
 * Uses WebSockets (port 443) to execute migrations.
 *
 * Usage:
 *   npm run migrate -- <migration_name>
 *
 * Example:
 *   npm run migrate -- init
 *   npm run migrate -- add_avatar_to_user
 */

import { execSync } from "child_process"
import { writeFileSync, mkdirSync, existsSync } from "fs"
import { join } from "path"
import { Pool, neonConfig } from "@neondatabase/serverless"
import "dotenv/config"

// Node 22+ has native WebSocket
neonConfig.webSocketConstructor = globalThis.WebSocket

const migrationName = process.argv[2]

if (!migrationName) {
    console.error("❌  Debes indicar un nombre para la migración.")
    console.error("    Ejemplo: npm run migrate -- add_avatar_to_user")
    process.exit(1)
}

if (!process.env.DATABASE_URL) {
    console.error("❌  DATABASE_URL no está definida en .env")
    process.exit(1)
}

// ─── 1. Generate SQL diff ────────────────────────────────────────────────────
// Strategy: diff from the last applied schema snapshot to the current schema.
// This avoids needing a shadow database or TCP port 5432.

const migrationsDir = join("prisma", "migrations")
const appliedSchemaPath = join("prisma", "schema.applied.prisma")
const hasAppliedSchema = existsSync(appliedSchemaPath)

// Ensure migrations dir exists
if (!existsSync(migrationsDir)) {
    mkdirSync(migrationsDir, { recursive: true })
}

// Ensure migration_lock.toml exists
const lockFile = join(migrationsDir, "migration_lock.toml")
if (!existsSync(lockFile)) {
    writeFileSync(lockFile, `# Please do not edit this file manually\n# It should be added in your version-control system (i.e. Git)\nprovider = "postgresql"\n`, "utf-8")
}

let sql: string

try {
    const fromFlag = hasAppliedSchema
        ? `--from-schema ${appliedSchemaPath}`
        : "--from-empty"

    sql = execSync(
        `npx prisma migrate diff ${fromFlag} --to-schema prisma/schema.prisma --script`,
        { encoding: "utf-8", stdio: ["pipe", "pipe", "pipe"] }
    ).trim()
} catch (err) {
    console.error("❌  Error generando el diff de Prisma:", err)
    process.exit(1)
}

if (!sql || sql.includes("-- This is an empty migration")) {
    console.log("✅  No hay cambios pendientes en el schema.")
    process.exit(0)
}

console.log("\n📋  SQL pendiente:\n")
console.log(sql)

// ─── 2. Save migration file ──────────────────────────────────────────────────

const timestamp = new Date()
    .toISOString()
    .replace(/\D/g, "")
    .slice(0, 14)

const migrationDir = join(migrationsDir, `${timestamp}_${migrationName}`)
mkdirSync(migrationDir, { recursive: true })
writeFileSync(join(migrationDir, "migration.sql"), sql, "utf-8")
console.log(`\n💾  Migración guardada en: ${migrationDir}/migration.sql`)

// ─── 3. Execute against Neon via WebSocket (port 443) ────────────────────────

console.log("\n🚀  Aplicando migración en Neon...\n")

const pool = new Pool({ connectionString: process.env.DATABASE_URL })
const client = await pool.connect()

try {
    await client.query(sql)
    console.log("✅  Migración aplicada correctamente.")

    // ─── 4. Update applied schema snapshot ──────────────────────────────────
    const { copyFileSync } = await import("fs")
    copyFileSync(join("prisma", "schema.prisma"), appliedSchemaPath)
    console.log("📸  Snapshot actualizado: prisma/schema.applied.prisma")
} catch (err) {
    console.error("❌  Error al ejecutar la migración:", err)
    process.exit(1)
} finally {
    client.release()
    await pool.end()
}

// ─── Scripts to run after changes to prisma/schema.prisma ───────────────────
//
//  1. Regenerate Prisma Client types:
//       npm run generate
//
//  2. Apply changes to the database:
//       npm run migrate -- describe_your_change
//
//  Example:
//       npm run migrate -- add_avatar_to_user
// ────────────────────────────────────────────────────────────────────────────
